config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
   root "products#index"

  # get 'products', to: "products#index"
  # get 'products/new', to: "products#new"
  # post 'products', to: "products#create"
  # get 'products/:id', to: "products#show"

  resources :products
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :author
end

app/models/account_history.rb
class AccountHistory < ApplicationRecord
  belongs_to :account_supplier
end

app/models/account_supplier.rb
class AccountSupplier < ApplicationRecord
  belongs_to :supplier

end

app/models/adress.rb
class Adress < ApplicationRecord
  belongs_to :addressable, polymorphic: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books
  has_one :account
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :adresses, as: :addressable
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :appointments
  has_many :patients, through: :appointments
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :adresses, as: :addressable

end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :appointments
  has_many :doctors, through: :appointments
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
  has_and_belongs_to_many :teachers
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_one :account_supplier
  has_one :account_history, through: :account_supplier
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_and_belongs_to_many :students

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def show; end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_url
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @product.update(product_params)
      redirect_to products_url(@product)
    else
      render :new, status: :unprocessable_entity
    end
  end
    
 
  def destroy
    if @product.destroy
      redirect_to products_url
    else
      redirect_to @product
    end
  end

 private
 
  def set_product
    @product = Product.find(params[:id])

  end

  def product_params
    params.require(:product).permit(:name, :quantidade, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjetoMvc</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_product.html.erb
<%= form_with(model: @product) do |form| %>
    <%= form.label :name %>
    <%= form.text_field :name %>

    <%= form.label :quantidade %>
    <%= form.number_field :quantidade %>

    <%= form.label :price %>
    <%= form.number_field :price %>

    <%= form.submit "salvar" %>


<% end %>

app/views/products/edit.html.erb
<%= render 'product' %>

<p><%= link_to 'voltar', products_path %></p>

app/views/products/index.html.erb
<h1><%= link_to 'criar produto', new_product_path %> </h1>


<% @products.each do |product| %>

    <h2><%= product.name %> </h2>
    <h2><%= product.price %> </h2>
    <h2><%= product.quantidade %> </h2>

    <p><%= link_to "ver produto", product %></p>.
    <p><%= link_to "editar um produto", edit_product_path(product) %></p>
    <p><%= link_to 'Delete', "products/#{product.id}", data: { "turbo-method": :delete, 'turbo-confirm': "Tem certeza?" } %></p>

<% end %>

app/views/products/new.html.erb
<%= render 'product' %>

<p><%= link_to 'voltar', products_path %></p>

app/views/products/show.html.erb
<%= @product.name %>
<%= @product.quantidade %>
<%= @product.price %>
<%= @product.created_at %>

<p><%= link_to 'voltar', products_path %></p>